@extends('layouts.getquote')
@section('content')

<!-- header close  -->
<section class="get-section">
    <div class="container">
    <h4>Terms of Use</h4>

    <div class="">
            <h5>You must not:</h5>
            <p>Show any material from the website in public.<br>Republish material from this website (including republication on another website).<br>Sell, rent or sub-license material from the website.<br>Reproduce duplicate, copy or otherwise exploit material on this website for a commercial purpose; redistribute material from this website.</p>
            <h5>Acceptable use:</h5>
            <p>You must not use this website in any way that causes, or may cause, damage to the website or impairment of the availability or accessibility of the website; or in any way which is unlawful, illegal, fraudulent or harmful, or in connection with any unlawful, illegal, fraudulent or harmful purpose or activity.</p>
            <p>You must not use this website to copy, store, host, transmit, send, use, publish or distribute any material which consists of (or is linked to) any spyware, computer virus, Trojan horse, worm, keystroke logger, rootkit or other malicious computer software.</p>
            <p>You must not use this website to transmit or send unsolicited commercial communications.<br>You must not use this website for any purposes related to marketing without Ejobs4Pros’s express written consent.</p>
            <p>You must not conduct any systematic or automated data collection activities (including without limitation scraping, data mining, data extraction and data harvesting) on or in relation to this website without Ejobs4Pros’s express written consent.</p>
            <h5>Responsibility of website visitors:</h5>
            <p>By operating the Site, Ejobs4Pros does not represent or imply that it endorses any or all of the contributed content, or that it believes such material to be accurate, useful or non-harmful. You are responsible for taking precautions as necessary to protect yourself and your computer systems from viruses, worms, trojan horses, and other harmful or destructive content. The Site may contain content that is offensive, indecent, or otherwise objectionable, as well as content containing technical inaccuracies, typographical mistakes, and other errors. Ejobs4Pros disclaims any responsibility for any harm resulting from the use by visitors of the Site.</p>
            <h5>Restricted access:</h5>
            <p>Access to certain areas of this website is restricted. Ejobs4Pros reserves the right to restrict access to areas of this website, or indeed this entire website, at Ejobs4Pros’s discretion.<br>If Ejobs4Pros provides you with a user ID and password to enable you to access restricted areas of this website or other content or services, you must ensure that the user ID and password are kept confidential.</p>
            <p>Ejobs4Pros may disable your user ID and password in Ejobs4Pros’s sole discretion without notice or explanation.</p>
            <h3 class="text-center">Ejobs4Pros and Client Relationship</h3>
            <h5>Definitions:</h5>
            <p><strong>Client</strong> means the person or organization that request or purchases services for Ejobs4pros.<br><strong>Agreement</strong> means the Project Proposal, Terms and Conditions and any other attached documents.<br><strong>Agreement</strong> means the Project Proposal, Terms and Conditions and any other attached documents.<br><strong>Project</strong> means the scope and purpose of the Client’s identified usage of the work product as described in the Project Proposal.<br><strong>Services</strong> mean all services and the work product to be provided to Client by Ejobs4Pros as described and otherwise further defined in the Project Proposal.<br><strong>Deliverables</strong> means the services and work product specified in the Project Proposal to be delivered by Ejobs4Pros to Client.<br><strong>Client Content</strong> means all materials, writing, images or other creative content provided by Client used in preparing or creating the Deliverables.<br><strong>Third Party Materials</strong> means proprietary third party materials which are incorporated into the Final Deliverables, including without limitation stock photography or illustration.<br><strong>Ejobs4Pros Tools</strong> means all design tools developed and/or used by Ejobs4Pros in performing the Services, including pre-existing and newly developed software including source code, Web authoring tools, type fonts, and application tools, together with any other software, or other inventions whether or not patentable, and general non-copyright able concepts such as website design, architecture, layout, navigational and functional elements.</p>
            <h5>Proposal:</h5>
            <p>The terms of this Agreement expires 30 days after being submitted to Client. If this Agreement expires, Ejobs4Pros may modify the Agreement and resubmit it to Client.</p>
            <h5>Compensation:</h5>
            <p><strong>Fees:</strong> Client agrees to pay Ejobs4Pros the fees listed in the Project Proposal, including all taxes.<br><strong>Expenses:</strong> Client will pay Ejobs4Pros expenses, including but not limited to:</p>
            <ul>
            <li>(a) Incidental and out-of-pocket expenses at cost plus Ejobs4Pros’s standard markup of 10%;</li>
            <li>(b) Mileage reimbursement, other than normal commuting, at $2.50 per mile;</li>
            <li>(c) Travel expenses, other than normal commuting, but including airfare and rental vehicles, with client approval.</li>
            </ul>
            <p><strong>Additional Costs:</strong> Pricing in the Project Proposal includes only Ejobs4Pros fees. Any other costs, such as hosting, art licensing or photography, will be billed to Client.<br><strong>Hosting Final Deliverables:</strong>Ejobs4Pros will host the Final Deliverables on Ejobs4Pross web space while the Project is under construction status. If the Final Deliverables are not completed by the completion date listed in the Project Proposal, and the delay is not caused by Ejobs4Pros, Client agrees to pay Ejobs4Pros $120 per month for hosting until the Final Deliverables are moved to Clients server.</p>
            <h5>Payment:</h5>
            <p><strong>Payment Schedule:</strong> Payment is due when Ejobs4Pros completes each milestone as listed in the Work Plan and Milestones schedule, and Client accepts the Deliverables for that milestone.<br><strong>Invoices:</strong> All invoices are payable within 21 days of receipt. Invoices shall list any expenses and additional costs as separate items.</p>
            <h5>Late Payment:</h5>
            <p><strong>Late Fee:</strong> A monthly service fee of 1.5 percent, or the maximum allowed by law, is payable on all overdue balances.<br><strong>Crediting Late Payments:</strong> Payments will be credited to late payments first, then to unpaid balances.<br><strong>Collection Expenses:</strong> Client shall pay all collection or legal fees caused by late payments.<br><strong>Withholding Delivery:</strong> Ejobs4Pros may withhold delivery and transfer of ownership of any current work if accounts are not current or overdue invoices are not paid in full.<br><strong>Withholding License:</strong> All grants of any license to use or transfer ownership of any intellectual property rights under this Agreement are conditioned on full payment, including all outstanding Additional Costs, Expenses, Fees, or any other charges.</p>
            <h5>Changes to Project Scope:</h5>
            <p><strong>Change Request:</strong> If Client wants to change the Scope of Work after acceptance of this Agreement, Client shall send Ejobs4Pros a written Change Order describing the requested changes in detail. Within 14 of receiving a Change Order, Ejobs4Pros will respond with a statement proposing Ejobs4Pross availability, additional fees, changes to delivery dates, and any modification to the Terms and Conditions. Ejobs4Pros will evaluate each Change Order at its standard rate and charges.<br><strong>Major Change:</strong> If Client requests are at or near 20% percent of the time required to produce Deliverables, or the value of the Scope of Services, Ejobs4Pros shall be entitled to submit a new and separate Proposal to Client for written approval. Ejobs4Pros shall not begin work on the revised services until he receives a fully signed revised proposal and any additional fees.<br><strong>Minor Change:</strong> If Client requests are not Major Changes, Client will be billed on a time and materials basis at Ejobs4Pross hourly rate of $85 per hour. Such charges shall be in addition to all other amount payable under this Agreement, despite any maximum budget, contract price or final price identified. Ejobs4Pros may extend or modify any delivery schedule or deadlines in the Agreement as may be required by such changes.<br><strong>Acceptance/Rejection:</strong> Client will have 14 days to respond in writing accepting or rejecting the new proposal. If Client rejects the proposal, Ejobs4Pros will not be obligated to perform any services beyond those in the original Agreement.</p>
            <h5>Delays:</h5>
            <p><strong>Ejobs4Pros Delays:</strong> Ejobs4Pros shall use all reasonable efforts to meet the Work Plan and Milestones delivery schedule. Ejobs4Pros may extend the due date for any Deliverable by giving written notice to Client. The total of all extensions shall not exceed 21 days.<br><strong>Client Delays:</strong> Client shall use all reasonable efforts to provide needed information, materials and approvals. Any delay by Client will result in a day-for-day extension of the due date for all Deliverables.<br><strong>General Delays:</strong> Any delay caused by conditions beyond the reasonable control of the parties shall not be considered a breach and will result in a day-for-day extension any performance due. Each party shall use reasonable efforts to notify the other party, in writing, of a delay. Conditions beyond the reasonable control of the parties include, but are not limited to, natural disasters, acts of government after the date of agreement, power failure, fire, flood, acts of God, labor disputes, riots, acts of war, terrorism and epidemics.</p>
            <h5>Evaluation and Acceptance:</h5>
            <p><strong>Testing:</strong> Ejobs4Pros will test and correct Deliverables using commercially reasonable efforts before providing Deliverables to Client.<br><strong>Approval Periods:</strong> Client shall, within 7 business days after receiving each Deliverable, notify Ejobs4Pros in writing of any failure to comply with the specification of the Project Proposal or of any other objections, corrections or changes required. Ejobs4Pros shall, within 14 business days of receiving Clients notification, correct and submit a revised Deliverable to Client. Client shall, within 7 business days of receiving a revised Deliverable, either approve the corrected version or make further changes. If after 3 corrections by Ejobs4Pros, Client finds the Deliverables are not acceptable, Client may terminate this agreement subject to the termination clauses of this Agreement. If Client fails to provide approval or comments during any approval period, those Deliverables will be considered approved and accepted. All objections, corrections and changes shall be subject to the terms and conditions of this Agreement.</p>
            <h5>Client Responsibilities:</h5>
            <p>Client acknowledges that it is responsible for performing the following in a reasonable and <strong>timely manner:</strong></p>
            <ul>
            <li>(a) Provide Client Content in a form suitable for use in the Deliverables without further preparation by Ejobs4Pros, unless otherwise specified in the Project Proposal;</li>
            <li>(b) Proofread all Deliverables. Client will be charged for correcting errors after the acceptance of any Deliverable;</li>
            <li>(c) Make decisions regarding other parties.</li>
            </ul>
            <h5>Accreditation and Acceptance:</h5>
            <p><strong>Accreditation:</strong> Ejobs4Pros shall be entitled to place accreditation, as a hyperlink or otherwise, in the form, size and location as incorporated by Ejobs4Pros in the Deliverables on each page of the Final Deliverables.<br><strong>Promotion:</strong> Ejobs4Pros retains the right to reproduce, publish and display the Deliverables in Ejobs4Pros’s portfolios and websites, in galleries, design periodicals and other media or exhibits for the purposes of recognition of creative excellence or professional advancement, and to be credited with authorship of the Deliverables in connection with such uses. Promotional Approval: Either party, subject to the other’s reasonable approval, may describe its role in the Project on its website and in other promotional and marketing materials, and, if not expressly objected to, include a link to the other party’s website.</p>
            <h5>Confidential Information:</h5>
            <p>Client’s “Confidential Information” includes information that Ejobs4Pros should reasonably believe to be confidential. Ejobs4Pros’s “Confidential Information” includes the source code of any Ejobs4Pros Tools. All material considered confidential by either party shall be designated as confidential. Confidential Information shall not be disclosed to third parties and shall only be used as needed to perform this Agreement. Confidential Information shall not include any information that is already known by the recipient, becomes publicly known through no fault of the recipient, or is received from a third party without a restriction on disclosure.</p>
            <h5>Relationship of Parties:</h5>
            <p><strong>Independent Contractor:</strong> Ejobs4Pros is an independent contractor. Ejobs4Pros shall determine, in its sole discretion, the manner and means by which the Services are accomplished. No agency, partnership, joint venture, or employee-employer relationship is intended or created by this Agreement. Neither party is authorized to act as agent or bind the other party except as expressly stated in this Agreement. Ejobs4Pros and the work product or Deliverables prepared by Ejobs4Pros shall not be deemed a work for hire as defined under Copyright Law. All rights granted to Client are contractual in nature and are expressly defined by this Agreement. Ejobs4Pros shall be allowed to use third party’s as independent contractors in connection with the Services.<br><strong>No Exclusivity:</strong> This Agreement does not create an exclusive relationship between the parties. Client is free to engage others to perform services of the same or similar nature to those provided by Ejobs4Pros, and Ejobs4Pros shall be entitled to offer and provide design services to others, solicit other clients and otherwise advertise the services offered by Ejobs4Pros.</p>
            <h5>Representations and Warrantees:</h5>
            <p><strong>By Client:</strong> Client represents and warrants to Ejobs4Pros that:</p>
            <ul>
            <li>(a) To the best of Client’s knowledge, use of the Client Content does not infringe the rights of any third party;</li>
            <li>(b) Client shall comply with the terms and conditions of any licensing agreements which govern the use of Third Party Materials;</li>
            <li>(c) Client will obtain all necessary and appropriate rights and licenses to grant license to Ejobs4Pros to use Third Party Materials.</li>
            </ul>
            <h5>By Ejobs4Pros:</h5>
            <p><strong>Ejobs4Pros represents and warranty to Client that: </strong></p>
            <ul>
            <li>(a) Ejobs4Pros will provide the Services identified in the Agreement in a professional and workmanlike manner;</li>
            <li>(b) Ejobs4Pros shall secure all necessary rights, title, and interest in and to the Final Deliverables, including Ejobs4Pros Tools, sufficient for Ejobs4Pros to grant the intellectual property rights provided in this Agreement;</li>
            <li>(c) To the best of Ejobs4Pros’s knowledge, the Deliverables will not violate the rights of any third parties;</li>
            <li>(d) If Client or third parties modify the Deliverables or use the Deliverables outside of the scope or purpose of this Agreement, all representations and warranties of Ejobs4Pros shall be void.</li>
            </ul>
            <p>EXCEPT FOR THE EXPRESS REPRESENTATIONS AND WARRANTIES STATED IN THIS AGREEMENT, EJOBS4PROS MAKES NO WARRANTIES WHATSOEVER. EJOBS4PROS EXPLICITLY DISCLAIMS ANY OTHER WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY FOR A PARTICULAR PURPOSE OR COMPLIANCE WITH LAWS OR GOVERNMENT RULES OR REGULATIONS APPLICABLE TO THE PROJECT.</p>
            <h5>Indemnification and Liability:</h5>
            <p><strong>By Client:</strong> Client shall indemnify Ejobs4Pros from any and all damages, liabilities, costs, losses, expenses or attorney fees arising out of any claim, demand, or action by a third party arising out of any breach of Client’s responsibilities or obligations, representations or warranties under this Agreement. Ejobs4Pros shall promptly notify Client in writing of any third party claim or suit. Client shall have the right to fully control the defense and any settlement of such claim or suit.</p>
            <p><strong>By Developer:</strong> In the case of a third party lawsuit or proceeding based on a claim that Deliverables breach the third party’s intellectual property rights, and it is determined that such infringement has occurred, Ejobs4Pros may at its own expense, replace any infringing content with non-infringing content.</p>
            <p>Limitation of Liability. THE SERVICES AND THE WORK PRODUCT OF EJOBS4PROS ARE SOLD “AS IS.” IN ALL CIRCUMSTANCES, THE MAXIMUM LIABILITY OF EJOBS4PROS, ITS DIRECTORS, OFFICERS, EMPLOYEES, CONTRACTORS AND AFFILIATES (“EJOBS4PROS PARTIES”), TO CLIENT FOR DAMAGES FOR ANY AND ALL CAUSES WHATSOEVER, AND CLIENT’S MAXIMUM REMEDY, REGARDLESS OF THE FORM OF ACTION, WHETHER IN CONTRACT, TORT OR OTHERWISE, SHALL BE LIMITED TO THE NET PROFIT OF EJOBS4PROS. IN NO EVENT SHALL EJOBS4PROS BE LIABLE FOR ANY LOST DATA OR CONTENT, LOST PROFITS, BUSINESS INTERRUPTION OR FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY OR PUNITIVE DAMAGES ARISING OUT OF OR RELATING TO THE MATERIALS OR THE SERVICES PROVIDED BY EJOBS4PROS, EVEN IF EJOBS4PROS HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES, AND NOTWITHSTANDING THE FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.</p>
            <h5>Terms and Termination:</h5>
            <p><strong>Term:</strong> This agreement shall begin when both parties sign and shall continue until all Services are complete and delivered, or until the Agreement is “Terminated”.<br><strong>Termination for Cause:</strong> Either party may terminate this agreement at any time, on 14 days prior written notice if the other party breaches any of its material responsibilities or obligations under this Agreement and fails to cure that breach during that 14 day period.<br><strong>Termination for Insolvency:</strong> Either party may terminate this agreement at any time, on written notice to the other party, if the other party ceases to conduct business in its normal course; makes an assignment for the benefit of creditors; is liquidated or otherwise dissolved; becomes insolvent; files a petition in bankruptcy; or a receiver, trustee, or custodian is appointed for it.<br><strong>Termination by Mutual Agreement:</strong> This agreement may be terminated by the mutual agreement of the parties.<br><strong>Termination for Convenience:</strong> Either party may terminate this agreement at any time and for any reason, 21 days prior written notice to the other party. If Client terminates the Agreement under this section, Ejobs4Pros shall, at Clients reasonable discretion, complete any work assigned or scheduled during the notice period in accordance with the terms and conditions of this Agreement.<br><strong>Termination Fees:</strong> In the event of termination, Client shall pay Ejobs4Pros for the Services performed through the date of termination in the amount of a prorated portion of the fees due.<br>Client shall pay all Expenses, Fees, and Additional Costs incurred through the date of termination.<br><strong>Intellectual Property:</strong> If Client terminates and on full payment of compensation, Ejobs4Pros grants Client right and title as provided by this Agreement with respect to those Deliverables provided and accepted by Client as of the date of termination.<br><strong>Confidential Information:</strong> On expiration or termination of this Agreement:</p>
            <ul>
            <li>(a) each party shall return or, at the disclosing party’s request, destroy the Confidential Information of the other party, and</li>
            <li>(b) all rights and obligations regarding Confidential Information shall survive.</li>
            </ul>
            <h5>Rights to Final Art:</h5>
            <p><strong>License:</strong> Ejobs4Pros grants to Client a non-exclusive, perpetual and worldwide license to use and display the Final Deliverables in accordance with this Agreement. The rights granted to Client are for use of the Final Deliverables in its original form only. Client may not change, create derivative works or extract portions of the Final Deliverables.<br><strong>Liquidation for unlicensed use:</strong> Additional use of any Deliverables by Client outside the scope of the license granted above requires additional fees. Ejobs4Pros shall be entitled to further compensation equal to 100% percent of the total original Project fee unless otherwise agreed in writing by both parties. In the event of non-payment, Ejobs4Pros shall be entitled to pursue all remedies under law and equity.</p>
            <h5>Rights to Deliverables other than Final Art:</h5>
            <p><strong>Client Content:</strong> Client Content is the exclusive property of the Client. Client grants Ejobs4Pros a nonexclusive, nontransferable license to use, reproduce, modify, display and publish the Client Content solely in connection with Ejobs4Pros’s performance of the Services and limited promotional uses of the Deliverables as authorized in this Agreement.<br><strong>Ejobs4Pros Tools:</strong> All Ejobs4Pros Tools are and shall remain the exclusive property of Ejobs4Pros. Ejobs4Pros grants Client a nonexclusive, nontransferable, perpetual, worldwide license to use the Ejobs4Pros Tools solely to the extent necessary with the Final Deliverables for the Project.</p>
            <h5>Support Services:</h5>
            <p><strong>Warranty Period:</strong> During the first 1 month following expiration of this Agreement, Ejobs4Pros shall provide up to 3 hours of Support Services at no additional cost to Client. Support Services means commercially reasonable technical support and assistance to maintain and update the Deliverables, including correcting any errors or Deficiencies. Requests for additional support will be billed on a time and materials basis at Ejobs4Pros’s hourly fees of $85 per hour.<br><strong>Maintenance Period:</strong> After the Warranty Period expires and at Client’s option, Ejobs4Pros will provide Support Services for the following 3 months for Ejobs4Pros’s hourly fees of $85 per hour.<br><strong>No Enhancements:</strong> The services in the Warranty Period and the Maintenance Period do not include enhancements to the Project or other services outside the scope of the Proposal.</p>
            <h5>Enhancements:</h5>
            <p>During the Maintenance Period, Client may request that Ejobs4Pros develop enhancements to the Deliverables. Ejobs4Pros shall exercise commercially reasonable efforts to prioritize Ejobs4Pros’s resources to create such enhancements. Client understands Ejobs4Pros may have preexisting obligations that may delay requested enhancements. Ejobs4Pros shall provide any enhancements on a time and materials basis at Ejobs4Pross hourly fees of $85 per hour.<br><strong>Alterations:</strong> Alteration of any Deliverable is prohibited without the express permission of Ejobs4Pros. Ejobs4Pros will be given the first opportunity to make the required alterations. Unauthorized alterations shall constitute additional use and will be billed accordingly.</p>
            <h5>Dispute Resolution:</h5>
            <p><strong>Negotiation:</strong> Parties agree to attempt to resolve any dispute by negotiation between the parties.<br><strong>Arbitration/Mediation:</strong> If parties are unable to resolve the dispute by negotiation, either party may start mediation and/or binding arbitration in a forum mutually agreed to by the parties.<br><strong>Litigation:</strong> In all other circumstances, the parties specifically consent to the local, state and federal courts located in the state of New Jersey. The parties waive any jurisdictional or venue defenses available to them and further consent to service of process by mail.<br><strong>Attorney Fees:</strong> Ejobs4Pros shall be entitled to recover its attorneys’ fees and costs in any dispute resolved by binding arbitration or litigation.</p>
            <h5>General:</h5>
            <p><strong>Modification/Waiver:</strong> Modifications to this Agreement must be in writing and signed by both parties. Failure by either party to enforce any right or seek to remedy any breach under this Agreement shall not be construed as a waiver of such rights nor shall a waiver by either party of default in one or more instances be construed as constituting a continuing waiver or as a waiver of any other breach.<br><strong>Notices:</strong> All notices under this Agreement shall be given in writing either by: (a) Fax or Email, with return confirmation of receipt; (b) Certified or Registered mail, with return receipt requested.<br><strong>No Assignment:</strong> Rights or obligations under this Agreement shall not be transferred, assigned or encumbered without the prior written consent of the other party.<br><strong>Governing Law:</strong> This Agreement shall be governed by the law of New Jersey.<br><strong>Severability:</strong> If any provision of this Agreement is held invalid or unenforceable, the remainder of this Agreement shall remain in full force and effect. Where possible the invalid or unenforceable provision shall be interpreted in such manner as to be effective and valid under applicable law.<br><strong>Complete Agreement:</strong> This Agreement is the entire understanding of the parties and supersedes all prior understandings and documents relating to the subject matter of this Agreement.</p>
            </div>
    </div>
</section> 
<!-- sectionc close  -->
<section class="get-f">
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d184552.57289742303!2d-79.51814179377936!3d43.71815566213178!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89d4cb90d7c63ba5%3A0x323555502ab4c477!2sToronto%2C%20ON%2C%20Canada!5e0!3m2!1sen!2sin!4v1678602016785!5m2!1sen!2sin" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
</section>
<!-- section close     -->   
@stop